version: '3.1'

networks:
  kafka:
    name: kafka
  mongo:
    name: mongo

volumes:
  mongo-data:

services:

  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: BGT
      MONGO_INITDB_DATABASE: tsl
    volumes:
      - mongo-data:/data/db:rw
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: BGT
      ME_CONFIG_MONGODB_URL: mongodb://root:BGT@mongodb:27017/
    networks:
      - mongo
  
  connect:
    image: cnfldemos/kafka-connect-datagen:0.6.0-7.3.0
    hostname: connect
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    volumes:
      - ./mongodb-kafka-connect-mongodb-1.9.1:/usr/share/confluent-hub-components/mongodb-kafka-connect-mongodb-1.9.1
    networks:
      - kafka
      - mongo
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt /usr/share/confluent-hub-components/mongodb-kafka-connect-mongodb-1.9.1
        /etc/confluent/docker/run
