version: '3.1'

networks:
  kafka:
    name: kafka
  mongo:
    name: mongo

volumes:
  mongo-data:

services:

  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: BGT
      MONGO_INITDB_DATABASE: tsl
    volumes:
      - mongo-data:/data/db:rw
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: BGT
      ME_CONFIG_MONGODB_URL: mongodb://root:BGT@mongodb:27017/
    networks:
      - mongo
  